version: '3'
services:
  unifi-protect:
    container_name: unifi-unvr-rd
    privileged: true
    tmpfs:
      - '/run'
      - '/run/lock'
      - '/tmp'
    volumes:
      - unvr-srv:/srv
      - unvr-data:/data
      - unvr-persistent:/persistent
    network_mode: 'host'
    restart: unless-stopped
    # image: arm64v8/debian:latest
    image: 'rdlugosz/unifi-protect-arm64'

volumes:
    unvr-srv:
      external: true
    unvr-data:
      external: true
    unvr-persistent:
      external: true

